services:
    _defaults: { autowire: true, autoconfigure: true, public: false }

    # Register EventListener onKernelResponse
    BugBuster\ClientHintsRequestBundle\EventListener:
        public: true
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }
